### ISSUE TITLE
robotpy_installer download robotpy fails

### ISSUE THREAD

**Issue by caloisio** [caloisio/mentorbot#1]
OS: Windows 10 Pro
Python: Python 3.9.6 amd64
Terminal: Git Bash

Following the instructions on https://robotpy.readthedocs.io/en/stable/install/robot.html#install-robotpy (summarized in [README.md](https://github.com/caloisio/mentorbot/blob/main/README.md)) in a fresh virtualenv, the command
```bash
$ py -3 -m robotpy_installer download robotpy
```
fails with strange behavior. The command appears to attempt to download multiple versions of robotpy (only the most recent version is desired) and then fails when resolving dependencies for each version (see attached output.txt).

Attempting to specify the latest version of robotpy (2021.2.8 as indicated by https://pypi.org/project/robotpy/#history) with
```bash
$ py -3 -m robotpy_installer download robotpy==2021.2.8
```
fails with
```
ERROR: Could not find a version that satisfies the requirement wpilib<2022.0.0.0,>=2021.3.1.0 (from robotpy) (from versions: none)
ERROR: No matching distribution found for wpilib<2022.0.0.0,>=2021.3.1.0
```

Session output:
[output.txt](https://github.com/caloisio/mentorbot/files/7065261/output.txt)

**Comment by virtuald** [comment]
This should be fixed now, let me know if it's not working for you.
